### ISSUE TITLE
Use Laravel Queues/Jobs instead of a Python script

### ISSUE THREAD

**Issue by supertassu** [UTRS2/utrs#13]
Laravel has a feature named [Queues](https://laravel.com/docs/7.x/queues) which allows to run PHP jobs in the background either on regular intervals or based on user actions. I think that it would make sense if the current `wikiactions` table/script would be converted to use triggered jobs instead. This would allow to reduce code duplication and make on-wiki actions more instant.

* [x] Block existence verification (#33)
* [x] User permission checking (#88)
* [x] Appeal table updating (#141)
* [x] Account verification (not needed when #12 is merged)
* [ ] Private data cleanup (#380)
* [x] Close expired `NOTFOUND` appeals

**Comment by dqwiki** [comment]
Since this can be done locally, I'm fine with this. Lets do one task at a time though, as I not only want to get the hang of it to help when I need to make one, but so that everything doesn't fail at once.
