### ISSUE TITLE
Tracking task for supporting other wikis than the English Wikipedia

### ISSUE THREAD

**Issue by supertassu** [UTRS2/utrs#378]
Definitely wanted:
* [x] Per-wiki templates (#376)
* [x] Per-wiki bans, with ability to make them global

Maybe wanted, not sure:
* [ ] Write some sort of user guide?
* [ ] Finish up translation support (#50)
* [ ] Move to `utrs.wmcloud.org` so that we don't have to announce that change on that many places? (#62)
* [ ] Add ability to add permissions to the global blocks/locks queue only but not globally on all queues

**Comment by SidChat93** [comment]
It supports other wikis. You will find "Where you are blocked?" when you try to file an appeal.

**Comment by Lionboys00** [comment]
Will fix soon

**Comment by ABirHAsan123-beep** [comment]
#443422

**Comment by ABirHAsan123-beep** [comment]
> Definitely wanted:
> 
> * [x]  Per-wiki templates ([Per-wiki templates #376](https://github.com/UTRS2/utrs/pull/376))
> * [x]  Per-wiki bans, with ability to make them global
> 
> Maybe wanted, not sure:
> 
> * [ ]  Write some sort of user guide?
> * [ ]  Finish up translation support ([Translation support #50](https://github.com/UTRS2/utrs/issues/50))
> * [ ]  Move to `utrs.wmcloud.org` so that we don't have to announce that change on that many places? ([Decommission UTRS 1 #62](https://github.com/UTRS2/utrs/issues/62))
> * [ ]  Add ability to add permissions to the global blocks/locks queue only but not globally on all queues

**Comment by ABirHAsan123-beep** [comment]
> Definitely wanted:
> 
> * [x]  Per-wiki templates ([Per-wiki templates #376](https://github.com/UTRS2/utrs/pull/376))
> * [x]  Per-wiki bans, with ability to make them global
> 
> Maybe wanted, not sure:
> 
> * [ ]  Write some sort of user guide?
> * [ ]  Finish up translation support ([Translation support #50](https://github.com/UTRS2/utrs/issues/50))
> * [ ]  Move to `utrs.wmcloud.org` so that we don't have to announce that change on that many places? ([Decommission UTRS 1 #62](https://github.com/UTRS2/utrs/issues/62))
> * [ ]  Add ability to add permissions to the global blocks/locks queue only but not globally on all queues

**Comment by 19RachelZoieJovie97** [comment]
Ok

**Comment by yatendra2342-png** [comment]
G

**Comment by Kishorsalvi12** [comment]
Hii team wikipedia dqwiki my wikipedia account is globally block 2017 to 2026 please unblock me soon as possible thanks my wikipedia account name kishor salvi

**Comment by orwah775** [comment]
مرحبًا،

أحاول تقديم استئناف لمنع حسابي في ويكيبيديا العربية، لكن ويكيبيديا العربية (arwiki) لا تظهر ضمن قائمة مواقع الويكي المتاحة للاستئناف في UTRS 3.

وجدت هذه المهمة #378 الخاصة بدعم مواقع ويكي متعددة، ولاحظت أنها أُعيد فتحها في 20 فبراير.

هل يمكن إرشادي إلى الطريقة الصحيحة لتقديم استئناف منع ويكيبيديا العربية حاليًا، أو توضيح ما إذا كان دعم arwiki سيُضاف إلى UTRS 3؟

شكرًا لكم.

**Comment by twinfire55002020infoorg-code** [comment]
Fuck you bitch

**Comment by jackbeckett051-arch** [comment]
Kids train land channel
