### ISSUE TITLE
Decommission UTRS 1

### ISSUE THREAD

**Issue by dqwiki** [UTRS2/utrs#62]
While we aren't ready for this just yet, its good to make this a known project goal (maybe a milestone too).

### Pre-Requirements:
- [x] Current tool administrators for enwiki need to sign off that all templates have been transferred
- [x] Old appeals needs to be fully functional (#47 , possibly more)
- [ ] All private data needs to be ensured it's removed from the database #63 
- [x] Alpha needs to be made available #61 :question:
- [x] Change [[utrs:]] interwiki prefix and https://en.wikipedia.org/wiki/Template:UTRS
- [x] Get accepted OAuth consumer for new domain

### Day of requirements:
- [x] All UTRS 1 data should be transferred to a read-only state for archive purposes
- [x] Sandbox needs to be configured as the "Alpha" server w/OAuth setup for ACC OAuth wiki to save duplication
- [ ] Playground needs to be configured as the "beta" server w/OAuth setup for WMF wikis
- [ ] Beta domain needs to be transferred to the regular domain 
- [ ] Possibly implement new domain name (under [new wmcloud.org](wmcloud.org) (https://wikitech.wikimedia.org/wiki/Wikimedia_Cloud_Services_team/EnhancementProposals/DNS_domain_usage)?)
- [x] Shutdown and destroy utrs-production-2
- [x] File Phab task to note we no longer need the floating IP (not that we do even now)

**Comment by dqwiki** [comment]
I have diverted utrs. to the same IP as utrs-beta. but obviously that 404s because of laravels config.

**Comment by supertassu** [comment]
> 
> 
> I have diverted utrs. to the same IP as utrs-beta. but obviously that 404s because of laravels config.

This has broken old URLs, which I don't believe is an option. There are essentially three ways to implement redirects from old URLs to new ones: in Laravel routes file, in web server configuration and as a separate service (either using PHP to create files that redirect the user or something like Flask with Python).

Using Laravel routes file has some problems (for example, get parameters can cause some issues) but I have no preferences on the other options.

**Comment by dqwiki** [comment]
The old interface needed to be nuked either way as it likely had vulnerabilities we didn't know about.
That said, I have no objection to whichever method we decide to help reform these. Would putting PHP files in /public that redirect it help? I'm not deadset on whatever way is chosen.

**Comment by supertassu** [comment]
> The old interface needed to be nuked either way as it likely had vulnerabilities we didn't know about.

agreed, let's get rid of it


> That said, I have no objection to whichever method we decide to help reform these. Would putting PHP files in /public that redirect it help? I'm not deadset on whatever way is chosen.

that depends on web server configuration - in most cases it should work. Laravel's current config makes it inconvenient to add a new separate domain for this one url (`appeal.php`).

**Comment by MarcoAurelioWM** [comment]
The [[utrs:]] IW link was updated in https://meta.wikimedia.org/w/index.php?title=Talk:Interwiki_map&oldid=23383144#utrs
