### ISSUE TITLE
Insights/analytics dashboard

### ISSUE THREAD

**Issue by dqwiki** [UTRS2/utrs#718]
Create charts/reports via a dashboard for:
- [x] #723 🛑 
- [ ] The use of #717 (developer only, periodic publication via report as needed)
- [ ] Emails verified percentage #438 (developer only, periodic publication via report as needed)
- [ ] Amount of appeals transferred to ACC #634 (public)
- [ ] Amount of times appeal mapping is used collating users/appeal number in dynamic ways #635 (public)
- [ ] Number of errors counted on UTRS - Task TBC (public)
- [x] Number of appeals that are approved, rejected, expired by time period
- [ ] Average number of appeals per user over time re. continuous appeals #635 

Using: https://lavacharts.com/

More to come

**Comment by ABirHAsan123-beep** [comment]
#818

**Comment by ABirHAsan123-beep** [comment]
![git .txt](https://github.com/UTRS2/utrs/files/15279951/git.txt)
