### ISSUE TITLE
Final testing plan for UTRS 3

### ISSUE THREAD

**Issue by dqwiki** [UTRS2/utrs#759]
The following pages will be tested in English:
- [x] Mainpage
- [x] Appeal my block - account - No proxy
- [x] Appeal my block - account - Proxy
- [x] Appeal my block - IP - No proxy
- [x] Appeal my block - IP - Proxy
- [x] View my appeal from front page
- [ ] Reset key email
- [x] Admin - Manage bans
- [ ] Admin - Manage Templates
- [x] Admin - Manage Users
- [x] Admin - View logs
- [x] Admin - email bans
- [ ] Statistics - each chart/wiki
- [x] Supported wikis list
- [x] User preferences
- [ ] Quick and advanced search
- [ ] Pagination on appeals chart
- [ ] Admin review - Appeal page
- [ ] Admin review - each status
- [x] Admin review - with CU data
- [x] Admin review - with additional comments
- [x] Admin review - with translated comments
- [x] Admin review - with user reply
- [ ] Admin review - with admin reply
- [ ] Admin review - Appeal map accounts
- [ ] Admin review - Appeal map IPs
- [ ] Admin review - Able to click through other items on appeal map
- [x] Dev create an API key

The following pages will be tested in template name:
- [x] Mainpage
- [ ] Appeal my block - account - No proxy
- [ ] Appeal my block - account - Proxy
- [ ] Appeal my block - IP - No proxy
- [ ] Appeal my block - IP - Proxy
- [ ] View my appeal from front page
- [ ] Reset key email
- [x] Admin - Manage bans
- [ ] Admin - Manage Templates
- [ ] Admin - Manage Users
- [ ] Admin - View logs
- [ ] Admin - email bans
- [ ] Statistics - each chart/wiki
- [ ] Supported wikis list
- [ ] User preferences
- [ ] Quick and advanced search
- [ ] Pagination on appeals chart
- [x] Admin review - Appeal page
- [ ] Admin review - each status
- [ ] Admin review - with CU data
- [ ] Admin review - with additional comments
- [ ] Admin review - with translated comments
- [ ] Admin review - with user reply
- [ ] Admin review - with admin reply
- [ ] Admin review - Appeal map accounts
- [ ] Admin review - Appeal map IPs
- [ ] Admin review - Able to click through other items on appeal map
- [x] Individual emails

The following functionality has to be confirmed:
- [ ] Reset key email - spam protection #635
- [x] No email on file error #626
- [x] User preferences - email set #626
- [x] User preferences - Language set and translations #50
- [ ] Admin vs. user privileges #50
- [ ] ACC on appeal map #634
- [ ] Sending admin notifications on user updates #626
- [ ] Ensure appeal map IP reports aren't linked unless under same email #635 
- [ ] On wiki updater from PHP to python because of having to scrap package on upgrade
- [x] Test Email ban for admins #438 
- [ ] Test IP and user email bans #438
- [ ] Ensure user@wiki email bans are working correctly #438
- [ ] ACC inbound testing #634 
- [ ] ACC outbound mocking - will require further testing eventually #634 

QOL changes:
- [x] separate developer appeals page
- [x] Have a better email template preview system avail to devs

**Comment by hyq3** [comment]
Blocking people 👤 okay, it is not over yet.….

**Comment by anikmolla786** [comment]
This action can only be performed by users who are not logged in.

**Comment by anikmolla786** [comment]
Kust get block one foolest admins will make you crazy like, AI generated, We don't want your regrateness and no please just mention the thing you blocked for. I mean seriously what type of admins are those didn’t even know why users get blocked.

**Comment by radmahzad20-jpg** [comment]
> The following pages will be tested in English:
> 
> * [x]  Mainpage[x]  Appeal my block - account - No proxy[x]  Appeal my block - account - Proxy[x]  Appeal my block - IP - No proxy[x]  Appeal my block - IP - Proxy[x]  View my appeal from front page[ ]  Reset key email[x]  Admin - Manage bans[ ]  Admin - Manage Templates[x]  Admin - Manage Users[x]  Admin - View logs[x]  Admin - email bans[ ]  Statistics - each chart/wiki[x]  Supported wikis list[x]  User preferences[ ]  Quick and advanced search[ ]  Pagination on appeals chart[ ]  Admin review - Appeal page[ ]  Admin review - each status[x]  Admin review - with CU data[x]  Admin review - with additional comments[x]  Admin review - with translated comments[x]  Admin review - with user reply[ ]  Admin review - with admin reply[ ]  Admin review - Appeal map accounts[ ]  Admin review - Appeal map IPs[ ]  Admin review - Able to click through other items on appeal map[x]  Dev create an API key
> 
> The following pages will be tested in template name:
> 
> * [x]  Mainpage[ ]  Appeal my block - account - No proxy[ ]  Appeal my block - account - Proxy[ ]  Appeal my block - IP - No proxy[ ]  Appeal my block - IP - Proxy[ ]  View my appeal from front page[ ]  Reset key email[x]  Admin - Manage bans[ ]  Admin - Manage Templates[ ]  Admin - Manage Users[ ]  Admin - View logs[ ]  Admin - email bans[ ]  Statistics - each chart/wiki[ ]  Supported wikis list[ ]  User preferences[ ]  Quick and advanced search[ ]  Pagination on appeals chart[x]  Admin review - Appeal page[ ]  Admin review - each status[ ]  Admin review - with CU data[ ]  Admin review - with additional comments[ ]  Admin review - with translated comments[ ]  Admin review - with user reply[ ]  Admin review - with admin reply[ ]  Admin review - Appeal map accounts[ ]  Admin review - Appeal map IPs[ ]  Admin review - Able to click through other items on appeal map[x]  Individual emails
> 
> The following functionality has to be confirmed:
> 
> * [ ]  Reset key email - spam protection [Make appeals continuous vs. independent (Accounts only) #635](https://github.com/UTRS2/utrs/issues/635)[x]  No email on file error [Send admins notifications about appeals #626](https://github.com/UTRS2/utrs/issues/626)[x]  User preferences - email set [Send admins notifications about appeals #626](https://github.com/UTRS2/utrs/issues/626)[x]  User preferences - Language set and translations [Translation support #50](https://github.com/UTRS2/utrs/issues/50)[ ]  Admin vs. user privileges [Translation support #50](https://github.com/UTRS2/utrs/issues/50)[ ]  ACC on appeal map [ACC Appeal transfer #634](https://github.com/UTRS2/utrs/issues/634)[ ]  Sending admin notifications on user updates [Send admins notifications about appeals #626](https://github.com/UTRS2/utrs/issues/626)[ ]  Ensure appeal map IP reports aren't linked unless under same email [Make appeals continuous vs. independent (Accounts only) #635](https://github.com/UTRS2/utrs/issues/635)[ ]  On wiki updater from PHP to python because of having to scrap package on upgrade[x]  Test Email ban for admins [Enable emails and allow onwiki account verification #438](https://github.com/UTRS2/utrs/issues/438)[ ]  Test IP and user email bans [Enable emails and allow onwiki account verification #438](https://github.com/UTRS2/utrs/issues/438)[ ]  Ensure user@wiki email bans are working correctly [Enable emails and allow onwiki account verification #438](https://github.com/UTRS2/utrs/issues/438)[ ]  ACC inbound testing [ACC Appeal transfer #634](https://github.com/UTRS2/utrs/issues/634)[ ]  ACC outbound mocking - will require further testing eventually [ACC Appeal transfer #634](https://github.com/UTRS2/utrs/issues/634)
> 
> QOL changes:
> 
> * [x]  separate developer appeals page[x]  Have a better email template preview system avail to devs
