### ISSUE TITLE
Add ban management (master task)

### ISSUE THREAD

**Issue by dqwiki** [UTRS2/utrs#83]
We are already at the point in which bans need to be able to be made, and 3 bans have already been issued though the database. Tool Administrators need to be able to start making them and not just viewing them.

Bugs already existing in the code:
- [x] Bans are applied regardless of expiry (#84)
- [x] Bans need the ability to be hidden from tooladmin (#82)

Bugs that may get introduced (please comment on each in issue saying you checked it):
- [x] The visible log table on the blade file needs to hide protected entries (#82)
- [x] Modifying the block should not show non-privacy/OS the protected target (#82)
- [ ] Regex may be sanitized being put into the database

Features required:
- [ ] Valid regex validation for usernames
- [x] IP range selection with a dropdown of /16 to /64 for both IPv4 & IPv6
- [x] Logs of all changes to the ban on the view and/or modify page (whatever is created)
- [x] Expiry set by phrases like "2 weeks" (OR if not, a calendar dropdown that formats into a timestamp in textbox)
- [x] Additional suppression checkbox w/proper logging (#82)

Required logging:
- [x] Each ban create request
- [x] Each ban modify request

**Comment by dqwiki** [comment]
@supertassu Can we figure out where we are with this task again?

**Comment by supertassu** [comment]
I think we have everything else than RegEx-based username bans. How important are those?

**Comment by dqwiki** [comment]
With #349 filled, i'm closing this out.
